FROM alpine:latest

# ENV PORT=3080



RUN apk update
RUN apk add py-pip
RUN apk add --no-cache python3-dev 
RUN pip install --upgrade pip
# COPY requirements.txt/app/
WORKDIR /app



COPY . /app


ENV con_no. = 1

RUN pip --no-cache-dir install -r requirements.txt
COPY . .
ENV PORT = 3080
EXPOSE 3080
CMD ["python3", "app.py"]